# Generated by Django 5.0.6 on 2024-07-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropYieldInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('area', models.CharField(max_length=255)),
                ('average_rain_fall_mm_per_year', models.FloatField()),
                ('pesticides_tonnes', models.FloatField()),
                ('avg_temp', models.FloatField()),
            ],
        ),
    ]
