services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: agri-api
      MYSQL_USER: root
      MYSQL_PASSWORD: agri
      MYSQL_ROOT_PASSWORD: agri
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    command: ./wait-for-it.sh db:3306 -- python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/apis
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  mysql_data:
