services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: agri-api
      MYSQL_USER: root
      MYSQL_PASSWORD: agri
      MYSQL_ROOT_PASSWORD: agri
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

  web:
    build: .
    command: ./wait-for-it.sh db:3306 -- python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/apis
    ports:
      - "3306:3306"
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
