# Generated by Django 5.0.6 on 2024-06-22 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(max_length=50)),
                ('input_description', models.TextField(blank=True, null=True)),
                ('date_trained', models.DateTimeField(auto_now_add=True)),
                ('accuracy', models.CharField(blank=True, default='N/A', max_length=10)),
                ('f1_score', models.CharField(blank=True, default='N/A', max_length=10)),
                ('precision', models.CharField(blank=True, default='N/A', max_length=10)),
                ('recall', models.CharField(blank=True, default='N/A', max_length=10)),
                ('regressor_score', models.CharField(blank=True, default='N/A', max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
