# Generated by Django 5.0.6 on 2024-07-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelmetadata',
            name='accuracy',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='modelmetadata',
            name='f1_score',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='modelmetadata',
            name='precision',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='modelmetadata',
            name='recall',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='modelmetadata',
            name='regressor_score',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
    ]
